### ISSUE TITLE
Add script to update the asset list in main README

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/katalog#45]
https://github.com/machine-learning-exchange/katalog#list-of-default-katalog-assets

This list needs to reflect the actual assets in the katalog and indicate if it is featured based on `bootstrapper/catalog_upload.json` in `mlx` repo.

And of course the links need to be verified (see #43)

**Comment by ckadner** [comment]
There are some related already existing scripts that could be helpful to look at:

- [mlx/tools/regenerate_catalog_upload_json.py](https://github.com/machine-learning-exchange/mlx/blob/main/tools/python/regenerate_catalog_upload_json.py):
  finds all `*.yaml` files in the `katalog` repo and generates the [mlx/bootstrapper/catalog_upload.json](https://github.com/machine-learning-exchange/mlx/blob/main/bootstrapper/catalog_upload.json) file
  
- [katalog/tools/python/verify_doc_links.py](https://github.com/machine-learning-exchange/katalog/blob/main/tools/python/verify_doc_links.py): finds and verifies all URL and self-referential links in `*.yaml` and `*.md` files

**Comment by ckadner** [comment]
@RRM123

**Comment by rafvasq** [comment]
@RRM123 I'm working on something similar in the MLX repo, are you working on this?
